# https://github.com/marketplace/actions/publish-vs-code-extension
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on
name: Build test and publish
on: [push, pull_request]
jobs:
  build:
    name: Build vsix and publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: |
        npm install -g vsce
        vsce package
    - name: Publish to vs marketplace
      if: startsWith(github.ref, 'refs/tags')
      uses: HaaLeo/publish-vscode-extension@v0
      with:
        pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
        registryUrl: https://marketplace.visualstudio.com